name: docker-fallback-prover

on:
  push:
    tags:
      - 'v*.*.*'

env:
  IMAGE_NAME: ghcr.io/polymerdao/fallback-prover

jobs:
  docker-build-fallback-prover:
    runs-on: ubuntu-22.04-16core
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.build-ref }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ env.IMAGE_NAME }}

          labels: |
            org.opencontainers.image.source=https://github.com/polymerdao/fallback-prover
            org.opencontainers.image.title=fallback-prover
            org.opencontainers.image.url=https://github.com/polymerdao/fallback-prover

      - name: Authenticate Docker
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set version
        run: echo "VERSION=$( ./scripts/version.sh fallback-prover )" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64
          push: true
          file: Dockerfile
          provenance: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            VERSION=${{ env.VERSION }}
            TOKEN=${{ secrets.PACKAGES_TOKEN }}
          cache-from: type=registry,ref=${{ env.IMAGE_NAME }}:buildcache
          cache-to: type=registry,ref=${{ env.IMAGE_NAME }}:buildcache,mode=max

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: ${{ env.IMAGE_NAME }}:latest
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
