name: Unit Tests

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        cache: true
    - name: Cache Go modules
      uses: actions/cache@v4
      with:
        path: ${{env.GOPATH}}/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Configure Git credentials
      run: |
        git config --global credential.helper 'cache --timeout=3600'
        git config --global url."https://x-access-token:${{ secrets.PACKAGES_TOKEN }}@github.com/".insteadOf "https://github.com/"

    - name: Install dependencies
      env:
        GOPRIVATE: github.com/polymerdao/*
      run: go build ./...    

    - name: Run tests
      run: go test -v ./...
